### ISSUE TITLE
searchCatalog doesn't seem to consider "pageSize" in the request.

### ISSUE THREAD

**Issue by eelectronn** [googleapis/nodejs-datacatalog#114]
I constructed the request body as follows:
`request = {
    scope: {includeProjectIds: ['myprojectID']},
    query: 'someWord',
    pageSize: 5
}`
However, in response, it returns way more results than 5. And there is not nextPage token in the response.

**Comment by bcoe** [comment]
@alexander-fenster this is a little weird, is there a chance we defined the field wrong in the proto?

**Comment by alexander-fenster** [comment]
It auto-paginates automatically and fetches all the responses (this is the default behavior). To get just the first page with 5 results, pass `{autoPaginate: false}` as an options object (second parameter, after the request).

Quite soon, we'll have async iterators here to make it less weird :)

**Comment by eelectronn** [comment]
Great! That solved the problem. Thank you very much.
