### ISSUE TITLE
Enable samplegen in synth.py

### ISSUE THREAD

**Issue by ghost** [googleapis/nodejs-datacatalog#14]
Data Catalog team is starting to use the Sample Generator Tool. As we add samples setup to `datacatalog_gapic.yaml` (https://github.com/googleapis/googleapis/commit/3b943eb373600e969c247017ea05bb4ca62dfd68 for reference), we should also enable `synthool` to have NodeJS samples automatically generated.

To do so, we need to add `generator_args=["--dev_samples"]` to `synth.py` (see https://github.com/ricardosm-cit/nodejs-datacatalog/pull/2/files#diff-3620890cb174a7f98c0722895e37bb79).

**Comment by JustinBeckwith** [comment]
We're pulling back on this for now.
