### ISSUE TITLE
CI is broken on autosynth

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-datacatalog#231]
Looks like the system tests are failing on re-gen 😱

**Comment by sofisl** [comment]
Thanks for submitting, Justin. I think the issue is [here](https://github.com/googleapis/nodejs-datacatalog/pull/230/files#r567215500). For some reason, those types are being deleted during regeneration. I've reached out to @alexander-fenster for his thoughts!

**Comment by bcoe** [comment]
this is now fixed.
