### ISSUE TITLE
2.6 publish to npm

### ISSUE THREAD

**Issue by krychu83** [googleapis/nodejs-datacatalog#366]
Hi. Not sure if it is a right place to ask questions but do you have a plan to publish 2.6 to npm repositiory?

**Comment by meredithslota** [comment]
Hi @krychu83 — thank you for flagging this. It looks like the 2.6 release failed somehow — I've reopened that issue (#331) s we can look into it.

**Comment by meredithslota** [comment]
Hi @krychu83 — I found that we did indeed release 2.6.0 (here: https://github.com/googleapis/nodejs-datacatalog/releases/tag/v2.6.0, back in February) but it didn't make it all the way to npm. We re-triggered the release and it's there now: https://www.npmjs.com/package/@google-cloud/datacatalog as latest, although we also just released 3.0.0 two days ago and it's not there yet so I will also look into that. Thanks for letting us know!
