### ISSUE TITLE
Wrong name for entryGroupPath() in version 1.5.1

### ISSUE THREAD

**Issue by ricardolsmendes** [googleapis/nodejs-datacatalog#79]
Version _1.5.1_ shipped with the method `entrygroupPath()` instead of `entryGroupPath()`, as it used to be in previous versions. **This change breaks existing code**.

#### Environment details

  - OS: macOS Catalina
  - Node.js version: v13.3.0
  - npm version: 6.13.4
  - `@google-cloud/datacatalog` version: 1.5.1

#### Steps to reproduce

1. git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples
1. cd datacatalog/cloud-client
1. npm install
1. npm test

**Comment by ricardolsmendes** [comment]
@alexander-fenster

**Comment by alexander-fenster** [comment]
That's sad :(  We'll think and try to figure out what can be done here.

**Comment by alexander-fenster** [comment]
This is now fixed! https://github.com/googleapis/nodejs-datacatalog/blob/master/src/v1beta1/data_catalog_client.ts#L2685

**Comment by ricardolsmendes** [comment]
Cool! I'm waiting for the new version to be published so I'll run the system tests again.
